<?php

namespace AppBundle\Repository;

/**
 * PharmacyStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacyStockRepository extends \Doctrine\ORM\EntityRepository
{
}
