<?php

namespace AppBundle\Repository;

/**
 * SupplierStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierStockRepository extends \Doctrine\ORM\EntityRepository
{
}
